export const bookDetailsConfig = [
  // Dettagli Principali - Public Information
  {
    id: "titolo",
    label: "Titolo",
    type: "text",
    section: "Dettagli Principali",
    sectionOrder: 0,
    readOnly: true,
  },
  {
    id: "editore",
    label: "Editore",
    type: "select",
    options: "editori",
    section: "Dettagli Principali",
    sectionOrder: 0,
    store: {
      use: "useEditoriStore",
      name: "editoriStore",
      labelField: "editore",
    },
    readOnly: true,
  },
  {
    id: "collana",
    label: "Collana",
    type: "select",
    options: "collane",
    section: "Dettagli Principali",
    sectionOrder: 0,
    store: {
      use: "useCollaneStore",
      name: "collaneStore",
      labelField: "collana",
    },
    readOnly: true,
  },
  {
    id: "numeroCollana",
    label: "Numero Collana",
    type: "text",
    section: "Dettagli Principali",
    sectionOrder: 0,
    readOnly: true,
  },
  {
    id: "autore",
    label: "Autore",
    type: "text",
    section: "Dettagli Principali",
    sectionOrder: 0,
    readOnly: true,
  },
  {
    id: "edizioni",
    label: "Edizioni",
    type: "array",
    section: "Dettagli Principali",
    sectionOrder: 0,
    readOnly: true,
  },

  // Dettagli Secondari - Collector Information
  {
    id: "traduttore",
    label: "Traduttore",
    type: "text",
    section: "Dettagli Secondari",
    sectionOrder: 1,
    readOnly: true,
  },
  {
    id: "annoScrittura",
    label: "Anno Scrittura",
    type: "text",
    section: "Dettagli Secondari",
    sectionOrder: 1,
    readOnly: true,
  },
  {
    id: "annoPubblicazione",
    label: "Anno Pubblicazione",
    type: "text",
    section: "Dettagli Secondari",
    sectionOrder: 1,
    readOnly: true,
  },

  {
    id: "lingua",
    label: "Lingua",
    type: "select",
    options: "lingue",
    section: "Dettagli Secondari",
    sectionOrder: 1,
    store: {
      use: "useLingueStore",
      name: "lingueStore",
      labelField: "lingua",
    },
    readOnly: true,
  },

  // Dettagli Terzi - Admin Information
  {
    id: "ISBN",
    label: "ISBN",
    type: "text",
    section: "Dettagli Terzi",
    sectionOrder: 3,
    readOnly: true,
  },

  {
    id: "contiene",
    label: "Contiene",
    type: "text",
    section: "Dettagli Terzi",
    sectionOrder: 3,
    readOnly: true,
  },
  {
    id: "raccolta",
    label: "Raccolta",
    type: "text",
    section: "Dettagli Terzi",
    sectionOrder: 3,
    readOnly: true,
  },

  // Dettagli Sistema - SuperAdmin Information
  {
    id: "id",
    label: "Id",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
    calculated: true,
  },
  {
    id: "confermato",
    label: "Confermato",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
  },
  {
    id: "deleted",
    label: "Eliminato",
    type: "boolean",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
  },
  {
    id: "images",
    label: "Images",
    type: "array",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
  },
  {
    id: "defaultImageName",
    label: "Default Image Name",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
    calculated: true,
  },
  {
    id: "posseduto",
    label: "Posseduto",
    type: "boolean",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
    calculated: true,
  },
  {
    id: "deletedBy",
    label: "Eliminato da",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
  },
  {
    id: "deletedAt",
    label: "Data Eliminazione",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 4,
    readOnly: true,
  },
];
