export const bookDetailsConfig = [
  // Dettagli Principali - Public Information
  {
    id: "titolo",
    label: "Titolo",
    type: "text",
    section: "Dettagli Principali",
    sectionOrder: 5,
    readOnly: false,
  },
  {
    id: "editore",
    label: "Editore",
    type: "select",
    options: "editori",
    section: "Dettagli Principali",
    sectionOrder: 10,
    store: {
      use: "useEditoriStore",
      name: "editoriStore",
      labelField: "editore",
    },
    readOnly: false,
  },
  {
    id: "collana",
    label: "Collana",
    type: "select",
    options: "collane",
    section: "Dettagli Principali",
    sectionOrder: 20,
    store: {
      use: "useCollaneStore",
      name: "collaneStore",
      labelField: "collana",
    },
    readOnly: false,
  },
  {
    id: "numeroCollana",
    label: "Numero Collana",
    type: "text",
    section: "Dettagli Principali",
    sectionOrder: 30,
    readOnly: false,
  },
  {
    id: "autore",
    label: "Autore",
    type: "text",
    section: "Dettagli Principali",
    sectionOrder: 40,
    readOnly: false,
  },
  {
    id: "traduttore",
    label: "Traduttore",
    type: "text",
    section: "Dettagli Secondari",
    sectionOrder: 50,
    readOnly: false,
  },
  {
    id: "edizioni",
    label: "Edizioni",
    type: "array",
    section: "Dettagli Principali",
    sectionOrder: 60,
    readOnly: true,
  },
  {
    id: "annoPubblicazione",
    label: "Anno Pubblicazione",
    type: "select",
    options: Array.from(
      { length: new Date().getFullYear() - 1920 + 1 },
      (_, i) => {
        const year = 1920 + i;
        return { label: String(year), value: String(year) };
      },
    ),
    section: "Dettagli Secondari",
    sectionOrder: 70,
    readOnly: false,
  },

  {
    id: "lingua",
    label: "Lingua",
    type: "select",
    options: "lingue",
    section: "Dettagli Secondari",
    sectionOrder: 80,
    store: {
      use: "useLingueStore",
      name: "lingueStore",
      labelField: "lingua",
    },
    readOnly: false,
  },
  {
    id: "annoScrittura",
    label: "Anno Scrittura",
    type: "text",
    section: "Dettagli Secondari",
    sectionOrder: 90,
    readOnly: false,
  },

  {
    id: "ISBN",
    label: "ISBN",
    type: "text",
    section: "Dettagli Terzi",
    sectionOrder: 100,
    readOnly: false,
  },
  {
    id: "raccolta",
    label: "Raccolta",
    type: "text",
    section: "Dettagli Terzi",
    sectionOrder: 110,
    readOnly: false,
  },
  {
    id: "contiene",
    label: "Contiene",
    type: "text",
    section: "Dettagli Terzi",
    sectionOrder: 120,
    readOnly: false,
  },

  // Dettagli Sistema - SuperAdmin Information
  {
    id: "id",
    label: "Id",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 130,
    readOnly: true,
    calculated: true,
  },
  {
    id: "confermato",
    label: "Confermato",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 140,
    readOnly: true,
  },
  {
    id: "deleted",
    label: "Eliminato",
    type: "boolean",
    section: "Dettagli Sistema",
    sectionOrder: 150,
    readOnly: true,
  },
  {
    id: "images",
    label: "Images",
    type: "array",
    section: "Dettagli Sistema",
    sectionOrder: 160,
    readOnly: true,
  },
  {
    id: "defaultImageName",
    label: "Default Image Name",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 170,
    readOnly: true,
    calculated: true,
  },
  {
    id: "posseduto",
    label: "Posseduto",
    type: "boolean",
    section: "Dettagli Sistema",
    sectionOrder: 180,
    readOnly: true,
    calculated: true,
  },
  {
    id: "deletedBy",
    label: "Eliminato da",
    type: "text",
    section: "Dettagli Sistema",
    sectionOrder: 190,
    readOnly: true,
  },
  {
    id: "deletedAt",
    label: "Data Eliminazione",
    type: "date",
    section: "Dettagli Sistema",
    sectionOrder: 200,
    readOnly: true,
  },
];
